In [1]:
import pandas as pd
import numpy as np

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
Data=pd.read_csv('Diabetes.csv')
Data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [4]:
Data['Glucose']=np.where(Data['Glucose']==0,Data['Glucose'].median(),Data['Glucose'])
Data['Insulin']=np.where(Data['Insulin']==0,Data['Insulin'].median(),Data['Insulin'])

In [5]:
X=Data.drop('Outcome',axis=1)
y=Data['Outcome']

In [6]:
pd.DataFrame(X,columns=Data.columns[:-1])

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148.0,72,35,30.5,33.6,0.627,50
1,1,85.0,66,29,30.5,26.6,0.351,31
2,8,183.0,64,0,30.5,23.3,0.672,32
3,1,89.0,66,23,94.0,28.1,0.167,21
4,0,137.0,40,35,168.0,43.1,2.288,33
...,...,...,...,...,...,...,...,...
763,10,101.0,76,48,180.0,32.9,0.171,63
764,2,122.0,70,27,30.5,36.8,0.340,27
765,5,121.0,72,23,112.0,26.2,0.245,30
766,1,126.0,60,0,30.5,30.1,0.349,47
767,1,93.0,70,31,30.5,30.4,0.315,23

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=0)

In [8]:
# GENETIC ALGORITHMS

In [9]:
from sklearn.model_selection import RandomizedSearchCV
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
max_features = ['auto', 'sqrt','log2']
max_depth = [int(x) for x in np.linspace(10, 1000,10)]
min_samples_split = [2,5,10,14]
min_samples_leaf = [1,2, 4,6,8]

Param = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
              'criterion':['entropy','gini']}
print(Param)

{'n_estimators': [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000], 'max_features': ['auto', 'sqrt', 'log2'], 'max_depth': [10, 120, 230, 340, 450, 560, 670, 780, 890, 1000], 'min_samples_split': [2, 5, 10, 14], 'min_samples_leaf': [1, 2, 4, 6, 8], 'criterion': ['entropy', 'gini']}

from tpot import TPOTClassifier


TPOT_Classifier = TPOTClassifier(generations=5, population_size=24, offspring_size=12,
                                  verbosity=2, early_stop=12,
                                  config_dict={'sklearn.ensemble.RandomForestClassifier': Param}, 
                                  cv = 4, scoring = 'accuracy')



TPOT_Classifier.fit(X_train,y_train)

Accuracy = TPOT_Classifier.score(X_test, y_test)
print(Accuracy)

In [10]:
# OPTUNA

import optuna
import sklearn.svm
def objective(Trial):

   Classifier = Trial.suggest_categorical('classifier', ['RandomForest', 'SVC'])
    
   if Classifier == 'RandomForest':
        n_estimators = Trial.suggest_int('n_estimators', 200, 2000,10)
        max_depth = int(Trial.suggest_float('max_depth', 10, 100, log=True))

        clf = sklearn.ensemble.RandomForestClassifier(n_estimators=n_estimators, max_depth=max_depth)
   else:
        c = Trial.suggest_float('svc_c', 1e-10, 1e10, log=True)
        
        clf = sklearn.svm.SVC(C=c, gamma='auto')
        
   return sklearn.model_selection.cross_val_score(
        clf,X_train,y_train, n_jobs=-1, cv=3).mean()

Study = optuna.create_study(direction='maximize')
Study.optimize(objective, n_trials=100)

Trial = study.best_trial

print('Accuracy: {}'.format(Trial.value))
print("Best hyperparameters: {}".format(Trial.params))

Trial
Study.best_params

RF=RandomForestClassifier(n_estimators=330,max_depth=30)
RF.fit(X_train,y_train)

y_pred=RF.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))